version: "3.9"

services:

  rag-api:
    build: .
    ports:
      - "8000:8000"

  mlflow:
    image: ghcr.io/mlflow/mlflow
    command: mlflow server --host 0.0.0.0 --port 5000
    ports:
      - "5000:5000"